### ISSUE TITLE
Couldn't find any contact info so I'm here xD

### ISSUE THREAD

**Issue by SaltySoggy** [Justiniscoding/justiniscoding#1]
I was wondering of you found out a fix for your error message in HashLips...

"Illegal instruction: 4"

I am also getting it and its soooo annoying! :(

**Comment by Justiniscoding** [comment]
@SaltySoggy Unfortunately, I have not found any fixes for it.

**Comment by Justiniscoding** [comment]
I'll tell you if I figure out how to fix it

**Comment by Justiniscoding** [comment]
If you do not use your own images, does HashLips work? for me it does but when I use my own images I get the error

**Comment by SaltySoggy** [comment]
Make sure you changed your dimensions on 'config.js' line 46 and 47 to your images dimensions (should be in pixels)

I watched some youtube videos on it also, some form...

Reece Hunter - https://youtu.be/lFDpBmoD62A
and https://youtu.be/CQcMqe0k1Ig --- this one kinda walks you through how to draw and export the layers, I only used the how to export the layers part (its more towards the end)  

Good luck and hope that helps :)

**Comment by Justiniscoding** [comment]
Thank you! I never realized you had to change the image size
